apiVersion: v1
kind: Service
metadata:
  name: chrony-alpine-service
  #namespace: default
  labels:
    app: chrony-alpine
spec:
  ports:
  # port=available to other containers
  - port: 123
    name: ntp
    # targetPort=exposed from inside container
    targetPort: 123
    protocol: UDP
  selector:
    app: chrony-alpine
